version: '3.8'
services:
  shell:
    build: ./shell
    ports:
      - "3000:3000"
    networks:
      - ecom-net
  user:
    build: ./microfrontends/user
    ports:
      - "3001:3000"
    networks:
      - ecom-net
  catalog:
    build: ./microfrontends/catalog
    ports:
      - "3002:3000"
    networks:
      - ecom-net
  review:
    build: ./microfrontends/review
    ports:
      - "3003:3000"
    networks:
      - ecom-net
  search:
    build: ./microfrontends/search
    ports:
      - "3004:3000"
    networks:
      - ecom-net
  cart:
    build: ./microfrontends/cart
    ports:
      - "3005:3000"
    networks:
      - ecom-net
  payment:
    build: ./microfrontends/payment
    ports:
      - "3006:3000"
    networks:
      - ecom-net
  order:
    build: ./microfrontends/order
    ports:
      - "3007:3000"
    networks:
      - ecom-net
  logistics:
    build: ./microfrontends/logistics
    ports:
      - "3008:3000"
    networks:
      - ecom-net
  admin:
    build: ./microfrontends/admin
    ports:
      - "3009:3000"
    networks:
      - ecom-net
  marketing:
    build: ./microfrontends/marketing
    ports:
      - "3010:3000"
    networks:
      - ecom-net
  security:
    build: ./microfrontends/security
    ports:
      - "3011:3000"
    networks:
      - ecom-net
  invoicing:
    build: ./microfrontends/invoicing
    ports:
      - "3012:3000"
    networks:
      - ecom-net
  pwa:
    build: ./microfrontends/pwa
    ports:
      - "3013:3000"
    networks:
      - ecom-net
  seller:
    build: ./microfrontends/seller
    ports:
      - "3014:3000"
    networks:
      - ecom-net
  ai:
    build: ./microfrontends/ai
    ports:
      - "3015:3000"
    networks:
      - ecom-net
  cms:
    build: ./microfrontends/cms
    ports:
      - "3016:3000"
    networks:
      - ecom-net
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    networks:
      - ecom-net
  tests:
    build: ./tests
    networks:
      - ecom-net
networks:
  ecom-net:
    driver: bridge 